### ISSUE TITLE
base < 4.8 ?

### ISSUE THREAD

**Issue by alpmestan** [bmsherman/cublas#3]
Hello Ben,

Just today I wanted to pull _cublas_ in a project of mine and realized (well, cabal did it for me) that its bound for `base` is <4.8. Any hope to make it compatible with more recent `base`s/GHCs?

While I'm here, was there anything added in recent `cublas` versions that's not in this package? It's a bit hard to do a mental diff just by looking at the respective docs =)

Thanks!

**Comment by bmsherman** [comment]
The bound of `base` < 4.8 is simply because last time I adjusted things, 4.7 was the latest version. Have you tried upping the bound to 4.8 to see whether it would work?

The package uses a (relatively insane) Template Haskell program to read through the header files for CUBLAS and automatically make bindings to functions which follow a regular enough pattern. So any new functions whose interface is similar enough to current functions should just be given bindings automatically. But if there are some functions with different interfaces, it might not add them or it might throw a fit and fail with error; I'm not sure, and it might depend on what the new functionality would be.

I suggest that you try upping the bound on `base` and seeing if it compiles!

**Comment by alpmestan** [comment]
I am currently setting up the "pure-CUDA" side of things in my code at the moment, just happened to throw "cublas" in the deps and saw the error. I haven't explored further but will do and report when I get around to it. Thanks!

**Comment by tmcdonell** [comment]
@alpmestan I have uploaded a new version http://hackage.haskell.org/package/cublas-0.3.0.0

**Comment by alpmestan** [comment]
Cheers!
